name: aria-et
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytest
  - setuptools>=64
  - wheel
  - pip:
      - bids-validator-deno
      - psychopy==2026.2.1
      - tobii-research
